services:
  db:
    image: postgres:14
    container_name: postgres-event-management
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: