spring.application.name=event-management
spring.datasource.url=jdbc:postgresql://localhost:5432/event_db
spring.datasource.username=Miaouadmin
spring.datasource.password=MiaouMinoupassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect